2022-03-13 12:14:03 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration eskom_loadshedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-13 12:14:03 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-13 12:14:03 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-13 12:14:12 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=55 from 2022-03-13 03:15:16)
2022-03-13 12:14:27 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2022-03-13 12:14:37 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.eskom_loadshedding_stage (<class 'custom_components.eskom_loadshedding.sensor.EskomStageSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-03-13 12:14:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: Cannot connect to host 192.168.0.211:9939 ssl:default [Connect call failed ('192.168.0.211', 9939)]
2022-03-13 12:15:02 WARNING (MainThread) [homeassistant.components.switch] Updating adguard switch took longer than the scheduled update interval 0:00:10
2022-03-13 12:15:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:15:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:16:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:17:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:20:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:23:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:26:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:28:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:31:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:34:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:37:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:39:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:42:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:45:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:48:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:50:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:53:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:56:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 12:59:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:02:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:04:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:07:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:10:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:13:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:15:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:18:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:21:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:24:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:26:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:29:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:32:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:35:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:38:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:40:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:43:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:46:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:49:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:51:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:54:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 13:57:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:00:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:02:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:05:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:08:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:11:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:14:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:16:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:19:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:22:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:25:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:27:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:30:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:33:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:36:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:38:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:41:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:44:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:47:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:50:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:52:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:55:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 14:58:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:01:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:03:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:06:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:09:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:12:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:14:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:17:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:20:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:23:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:25:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:28:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:31:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:34:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:37:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:39:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:42:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:45:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:48:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:50:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:53:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:56:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 15:59:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:01:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:04:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:07:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:10:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:13:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:15:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:18:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:21:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:24:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:26:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:29:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:32:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:35:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:37:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:40:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:43:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:46:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:49:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:51:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:54:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 16:57:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:00:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:02:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:05:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:08:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:11:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:13:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:16:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:19:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:22:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:25:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:27:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:30:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:33:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:36:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:38:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:41:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:44:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:47:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:49:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:52:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:55:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 17:58:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:00:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:03:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:06:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:09:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:12:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:14:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:17:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:20:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:23:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:25:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:28:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:31:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:34:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:36:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:39:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:42:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:45:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:48:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:50:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:53:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:56:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 18:59:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:01:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:04:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:07:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:10:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:12:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:15:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:18:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:21:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:24:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:26:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:29:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:32:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:35:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:37:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:40:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:43:19 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'TimeoutError'
2022-03-13 19:43:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:46:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:48:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:51:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:54:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 19:57:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:00:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:02:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:05:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:08:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:11:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:13:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:16:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:19:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:22:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:24:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:27:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:30:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:33:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:36:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:38:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:41:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:44:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:47:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:49:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:52:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:55:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 20:58:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:00:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:03:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:06:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:09:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:11:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:14:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:17:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:20:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:23:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:25:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:28:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:31:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:34:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:36:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:39:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:42:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:45:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:47:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:50:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:53:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:56:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 21:59:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:01:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:04:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:07:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:10:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:12:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:15:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:18:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:21:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:23:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:26:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:29:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:32:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:35:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:37:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:40:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:43:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:46:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:48:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:51:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:54:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:57:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 22:59:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:02:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:05:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:08:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:11:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:13:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:16:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:19:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:22:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:24:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:27:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:30:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:33:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:35:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:38:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:41:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:44:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:46:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:49:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:52:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:55:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-13 23:58:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:00:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:03:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:06:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:09:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:11:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:14:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:17:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:20:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:22:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:25:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:28:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:31:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:34:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:36:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:39:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:42:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:45:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:47:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:50:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:53:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:56:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 00:58:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:01:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:04:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:07:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:10:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:12:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:15:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:18:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:21:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:23:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:26:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:29:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:32:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:34:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:37:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:40:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:43:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:46:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:48:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:51:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:54:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:57:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 01:59:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:02:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:05:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:08:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:10:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:13:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:16:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:19:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:22:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:24:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:27:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:30:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:33:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:35:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:38:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:41:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:44:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:46:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:49:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:52:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:55:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 02:57:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:00:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:03:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:06:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:09:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:11:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:14:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:17:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:20:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:22:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:25:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:28:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:31:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:33:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:36:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:39:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:42:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:45:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:47:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:50:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:53:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:56:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 03:58:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:01:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:04:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:07:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:09:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:12:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:15:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:18:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:21:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:23:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:26:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:29:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:32:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:34:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:37:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:40:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:43:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:45:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:48:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:51:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:54:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:57:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 04:59:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:02:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:05:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:08:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:10:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:13:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:16:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:19:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:21:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:24:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:27:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:30:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:32:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:35:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:38:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:41:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:44:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:46:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:49:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:52:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:55:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 05:57:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:00:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:03:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:06:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:08:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:11:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:14:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:17:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:20:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:22:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:25:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:28:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:31:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:33:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:36:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:39:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:42:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:44:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:47:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:50:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:53:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:56:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 06:58:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:01:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:04:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:07:06 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:09:52 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:12:38 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:15:24 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:18:10 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:20:56 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:23:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:26:29 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:29:15 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:32:01 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:34:47 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:37:33 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:40:19 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:43:05 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:45:51 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:48:37 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:51:23 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:54:09 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:56:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 07:59:42 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:02:28 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:05:14 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:08:00 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:10:46 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:13:32 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:16:18 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:19:04 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:21:50 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:24:36 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:27:22 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:30:08 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:32:55 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:35:41 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:38:27 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:41:13 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:43:59 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:46:45 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:49:31 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:52:17 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:55:03 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 08:57:49 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:00:35 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:03:21 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:06:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:08:54 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:11:40 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:14:26 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:17:12 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:19:58 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:22:44 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:25:30 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:28:16 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:31:02 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:33:48 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:36:34 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:39:20 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:42:07 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:44:53 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:47:39 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:50:25 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:53:11 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:55:57 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 09:58:43 WARNING (MainThread) [homeassistant.components.konnected.panel] Exception trying to connect to panel: 
2022-03-14 16:27:09 ERROR (MainThread) [homeassistant.components.ipp.coordinator] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.
2022-03-14 20:15:19 ERROR (MainThread) [homeassistant.components.ipp.coordinator] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.
2022-03-15 11:28:17 ERROR (MainThread) [homeassistant.components.ipp.coordinator] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.
2022-03-16 17:03:12 WARNING (MainThread) [zeroconf] Error with socket 11 (('192.168.0.200', 5353))): [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
2022-03-16 17:04:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:04:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:04:48 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2022-03-16 17:06:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:06:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:08:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:08:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:10:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:10:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:12:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:12:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:14:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:14:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:16:14 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: Error while resolving Forecast.Solar API address
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 72, in _request
    result = await dns.query("api.forecast.solar", "A")
aiodns.error.DNSError: (11, 'Could not contact DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 138, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 74, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address
2022-03-16 17:16:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:16:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:18:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:18:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:20:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:20:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:22:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:22:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:24:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:24:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:26:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:26:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:28:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:28:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:30:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:30:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:32:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:32:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:34:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:34:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:36:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:36:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:37:23 ERROR (MainThread) [custom_components.eskom_loadshedding] Error fetching eskom_loadshedding data: Cannot connect to host loadshedding.eskom.co.za:443 ssl:<ssl.SSLContext object at 0x7f77532a98c0> [Try again]
2022-03-16 17:38:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:38:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:40:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:40:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:42:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:42:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:44:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:44:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:46:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:46:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:47:30 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-03-16 17:48:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:48:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:50:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:50:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:52:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:52:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:54:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:54:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:56:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:56:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:58:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 17:58:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:00:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:00:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:02:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:02:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:04:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:04:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:06:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:06:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:08:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:08:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:08:53 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2022-03-16 18:10:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:10:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:12:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:12:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:14:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:14:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:14:42 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:15:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 287, in async_discover
    for host in await self._discover_hosts.async_discover():
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/discovery.py", line 143, in async_discover
    sys_network_data = await loop.run_in_executor(None, self._get_sys_network_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/discovery.py", line 137, in _get_sys_network_data
    sys_network_data.setup()
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/network.py", line 155, in setup
    self.network = get_network(self.local_ip, self.adapters)
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/network.py", line 74, in get_network
    return ip_network(f"{local_ip}/{network_prefix}", False)
  File "/usr/local/lib/python3.9/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: 'None/24' does not appear to be an IPv4 or IPv6 network
2022-03-16 18:15:06 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:15:06 ERROR (MainThread) [custom_components.hacs] <Integration hacs/integration> Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:16:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:16:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:16:30 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: Error while resolving Forecast.Solar API address
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 72, in _request
    result = await dns.query("api.forecast.solar", "A")
aiodns.error.DNSError: (11, 'Could not contact DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 138, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 74, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address
2022-03-16 18:18:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:18:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:20:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:20:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:22:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:22:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:24:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:24:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:24:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:26:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:26:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:28:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:28:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:30:23 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:30:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:32:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:32:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:34:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:34:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:34:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:36:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:36:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:38:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:38:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:40:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:40:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:42:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:42:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:44:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:44:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:44:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:46:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:46:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:48:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:48:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:50:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:50:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:52:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:52:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:54:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:54:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:54:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 18:56:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:56:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:58:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 18:58:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:00:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:00:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:02:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:02:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:04:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:04:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:04:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 19:06:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:06:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:08:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:08:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:10:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:10:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:12:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:12:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:12:58 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2022-03-16 19:14:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:14:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:14:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 19:15:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 287, in async_discover
    for host in await self._discover_hosts.async_discover():
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/discovery.py", line 143, in async_discover
    sys_network_data = await loop.run_in_executor(None, self._get_sys_network_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/discovery.py", line 137, in _get_sys_network_data
    sys_network_data.setup()
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/network.py", line 155, in setup
    self.network = get_network(self.local_ip, self.adapters)
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/network.py", line 74, in get_network
    return ip_network(f"{local_ip}/{network_prefix}", False)
  File "/usr/local/lib/python3.9/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: 'None/24' does not appear to be an IPv4 or IPv6 network
2022-03-16 19:16:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:16:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:16:46 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: Error while resolving Forecast.Solar API address
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 72, in _request
    result = await dns.query("api.forecast.solar", "A")
aiodns.error.DNSError: (11, 'Could not contact DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 138, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.9/site-packages/forecast_solar/__init__.py", line 74, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address
2022-03-16 19:18:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:18:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:20:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:20:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:22:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:22:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:24:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:24:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:24:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 19:26:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:26:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:28:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:28:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:30:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:30:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:32:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:32:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:34:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:34:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:34:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 19:36:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:36:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:38:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:38:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:40:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:40:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:42:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:42:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:44:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:44:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:44:43 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 427, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
2022-03-16 19:46:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:46:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:48:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:48:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:50:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:50:24 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=14 read=polling write=<idle, bufsize=0>>
2022-03-16 19:54:56 ERROR (MainThread) [frontend.js.latest.202203011] :0:0 Script error.
2022-03-16 19:56:18 ERROR (MainThread) [frontend.js.latest.202203011] :0:0 Script error.
2022-03-16 20:15:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 287, in async_discover
    for host in await self._discover_hosts.async_discover():
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/discovery.py", line 143, in async_discover
    sys_network_data = await loop.run_in_executor(None, self._get_sys_network_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/discovery.py", line 137, in _get_sys_network_data
    sys_network_data.setup()
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/network.py", line 155, in setup
    self.network = get_network(self.local_ip, self.adapters)
  File "/usr/local/lib/python3.9/site-packages/aiodiscover/network.py", line 74, in get_network
    return ip_network(f"{local_ip}/{network_prefix}", False)
  File "/usr/local/lib/python3.9/ipaddress.py", line 83, in ip_network
    raise ValueError('%r does not appear to be an IPv4 or IPv6 network' %
ValueError: 'None/24' does not appear to be an IPv4 or IPv6 network
2022-03-16 23:29:10 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2022-03-17 02:55:20 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-03-17 17:53:56 ERROR (MainThread) [homeassistant.components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 270, in async_find_device_wrapper
    await self.async_find_device(allow_exist)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 283, in async_find_device
    self.atv, self.atv_identifiers = await device_scan(
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 57, in device_scan
    scan_result = await scan(loop, timeout=3, hosts=_host_filter(), aiozc=aiozc)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 58, in scan
    aiozc, hosts=[IPv4Address(host) for host in hosts]
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 58, in <listcomp>
    aiozc, hosts=[IPv4Address(host) for host in hosts]
  File "/usr/local/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/local/lib/python3.9/ipaddress.py", line 1194, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in '2c0f:f4c0:118c:40e0:db:f108:bf16:6b22'
2022-03-17 22:56:56 ERROR (MainThread) [homeassistant.components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 270, in async_find_device_wrapper
    await self.async_find_device(allow_exist)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 283, in async_find_device
    self.atv, self.atv_identifiers = await device_scan(
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 57, in device_scan
    scan_result = await scan(loop, timeout=3, hosts=_host_filter(), aiozc=aiozc)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 58, in scan
    aiozc, hosts=[IPv4Address(host) for host in hosts]
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 58, in <listcomp>
    aiozc, hosts=[IPv4Address(host) for host in hosts]
  File "/usr/local/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/local/lib/python3.9/ipaddress.py", line 1194, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in '2c0f:f4c0:118c:40e0:db:f108:bf16:6b22'
2022-03-18 08:44:45 ERROR (MainThread) [homeassistant.components.ipp.coordinator] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.
2022-03-18 10:19:30 ERROR (MainThread) [homeassistant.components.apple_tv.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 270, in async_find_device_wrapper
    await self.async_find_device(allow_exist)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 283, in async_find_device
    self.atv, self.atv_identifiers = await device_scan(
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 57, in device_scan
    scan_result = await scan(loop, timeout=3, hosts=_host_filter(), aiozc=aiozc)
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 58, in scan
    aiozc, hosts=[IPv4Address(host) for host in hosts]
  File "/usr/local/lib/python3.9/site-packages/pyatv/__init__.py", line 58, in <listcomp>
    aiozc, hosts=[IPv4Address(host) for host in hosts]
  File "/usr/local/lib/python3.9/ipaddress.py", line 1307, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/local/lib/python3.9/ipaddress.py", line 1194, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in '2c0f:f4c0:118c:40e0:db:f108:bf16:6b22'
