2021-12-25 07:37:23 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eskom_loadshedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-25 07:37:23 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-25 07:37:34 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry HUAWEI WiFi WS5200 for upnp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/upnp/__init__.py", line 125, in async_setup_entry
    device = await Device.async_create_device(hass, location)
  File "/usr/src/homeassistant/homeassistant/components/upnp/device.py", line 61, in async_create_device
    upnp_device = await Device.async_create_upnp_device(hass, ssdp_location)
  File "/usr/src/homeassistant/homeassistant/components/upnp/device.py", line 54, in async_create_upnp_device
    return await factory.async_create_device(ssdp_location)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/client_factory.py", line 75, in async_create_device
    return await self._async_create_device(device_el, description_url)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/client_factory.py", line 88, in _async_create_device
    service = await self._async_create_service(service_desc_el, description_url)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/client_factory.py", line 145, in _async_create_service
    state_vars = self._create_state_variables(scpd_el)
  File "/usr/local/lib/python3.9/site-packages/async_upnp_client/client_factory.py", line 165, in _create_state_variables
    raise UpnpError("Could not find service state table element")
async_upnp_client.exceptions.UpnpError: ('Could not find service state table element', None)
2021-12-25 07:37:35 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.eskom_loadshedding_stage (<class 'custom_components.eskom_loadshedding.sensor.EskomStageSensor'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-25 07:44:46 ERROR (MainThread) [homeassistant.components.slack.notify] There was a Slack API error while sending to home-automation: SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'not_in_channel'}")
2021-12-25 08:45:44 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 154, in _handle_request
    await response.write(data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 514, in write
    await self._payload_writer.write(data)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 116, in write
    self._write(chunk)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-12-25 09:07:01 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /homeassistant/restart request
